# Generated by Django 5.0.4 on 2024-08-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bank_address_bank_tel_branch_address_branch_tel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['code']},
        ),
    ]
