# Generated by Django 5.1 on 2024-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(default='000000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='Default Bank Name', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('code', 'bank')},
        ),
    ]
