# Generated by Django 5.1 on 2024-08-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='bank',
            name='tel',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='tel',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='Default Bank Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='Default Branch Name', max_length=100),
        ),
    ]
